// Enum for trip request payment methods
export const Emojis = Object.freeze({
  BANANA: "banana",
  BEER: "beer_mug",
  BENTO: "bento_box",
  BIRTHDAY_CAKE: "birthday_cake",
  BREAD: "bread",
  BUBBLE_TEA: "bubble_tea",
  CHEESE_WEDGE: "cheese_wedge",
  CHERRIES: "cherries",
  CROISSANT: "croissant",
  CORN: "ear_of_corn",
  DANGO: "dango",
  DUMPLING: "dumpling",
  FISH_CAKE: "fish_cake_with_swirl",
  GRAPES: "grapes",
  HOT_DOG: "hot_dog",
  LEAFY_GREEN: "leafy_green",
  LOBSTER: "lobster",
  MOON_CAKE: "moon_cake",
  ODEN: "oden",
  SANDWICH: "sandwich",
  SHRIMP: "shrimp",
  SOFT_ICE_CREAM: "soft_ice_cream",
  SPAGHETTI: "spaghetti",
  SUSHI: "sushi",
  WAFFLE: "waffle",
  WATERMELON: "watermelon",
});
