// FoodEmoji enums
export const FoodEmoji = Object.freeze({
  AVOCADO: "avocado",
  BACON: "bacon",
  BANANA: "banana",
  BEER: "beer_mug",
  BENTO: "bento_box",
  BEVERAGE_BOX: "beverage_box",
  BIRTHDAY_CAKE: "birthday_cake",
  BLUEBERRIES: "blueberries",
  BOTTLE_WITH_POPPING_CORK: "bottle_with_popping_cork",
  BREAD: "bread",
  BROCCOLI: "broccoli",
  BUBBLE_TEA: "bubble_tea",
  BURRITO: "burrito",
  BUTTER: "butter",
  CANDY: "candy",
  CHEESE_WEDGE: "cheese_wedge",
  CHERRIES: "cherries",
  CLINKING_GLASSES: "clinking_glasses",
  COCKTAIL_GLASS: "cocktail_glass",
  COCONUT: "coconut",
  COOKED_RICE: "cooked_rice",
  COOKING: "cooking",
  CORN: "ear_of_corn",
  CROISSANT: "croissant",
  CUPCAKE: "cupcake",
  CURRY_RICE: "curry_rice",
  CUSTARD: "custard",
  DANGO: "dango",
  DOUGHNUT: "doughnut",
  DUMPLING: "dumpling",
  EGGPLANT: "eggplant",
  FISH_CAKE: "fish_cake_with_swirl",
  FORK_KNIFE_PLATE: "fork_and_knife_with_plate",
  FORTUNE_COOKIE: "fortune_cookie",
  GRAPES: "grapes",
  GREEN_SALAD: "green_salad",
  HONEY_POT: "honey_pot",
  HOT_BEVERAGE: "hot_beverage",
  HOT_DOG: "hot_dog",
  HOT_PEPPER: "hot_pepper",
  KIWI_FRUIT: "kiwi_fruit",
  LEAFY_GREEN: "leafy_green",
  LEMON: "lemon",
  LOBSTER: "lobster",
  MANGO: "mango",
  MELON: "melon",
  MOON_CAKE: "moon_cake",
  ODEN: "oden",
  OLIVE: "olive",
  OYSTER: "oyster",
  PANCAKES: "pancakes",
  PEACH: "peach",
  PEAR: "pear",
  PIE: "pie",
  PIZZA: "pizza",
  POPCORN: "popcorn",
  PRETZEL: "pretzel",
  ROASTED_SWEET_POTATO: "roasted_sweet_potato",
  SANDWICH: "sandwich",
  SHORTCAKE: "shortcake",
  SHRIMP: "shrimp",
  SOFT_ICE_CREAM: "soft_ice_cream",
  SPAGHETTI: "spaghetti",
  SQUID: "squid",
  STRAWBERRY: "strawberry",
  SUSHI: "sushi",
  TACO: "taco",
  TAKEOUT_BOX: "takeout_box",
  TANGERINE: "tangerine",
  TEACUP: "teacup_without_handle",
  TOMATO: "tomato",
  TROPICAL_DRINK: "tropical_drink",
  WAFFLE: "waffle",
  WATERMELON: "watermelon",
});

// SymbolEmoji enums
export const SymbolEmoji = Object.freeze({
  BOX: "card_file_box",
  FIRE: "fire",
  HIBISCUS: "hibiscus",
  LEFT_ARROW: "left_arrow",
  LEFT_ARROW_DISABLED: "left_arrow_disabled",
  LINK: "link",
  LOVE_LETTER: "love_letter",
  MIRROR_BALL: "mirror_ball",
  MULTIPLY: "multiply",
  PACKAGE: "package",
  PAGE: "page",
  PENCIL: "pencil",
  PLUS: "plus",
  RED_MULTIPLY: "red_multiply",
  RIGHT_ARROW: "right_arrow",
  RIGHT_ARROW_DISABLED: "right_arrow_disabled",
  SCISSORS: "scissors",
  SCROLL: "scroll",
  SPARKLING_HEART: "sparkling_heart",
  WASTEBASKET: "wastebasket",
});

// Face enums
export const FaceEmoji = Object.freeze({
  WORRIED_FACE: "worried_face",
});
